# Generated by Django 5.1.6 on 2025-03-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_platform_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
